// Vue/3_숫자야구/numberBaseball.vue
<template>
  <div>
    <h1>{{result}}</h1>  
    <form @submit.prevent="onSubmitForm">
      <input ref="answer" minlength="4" maxlength="4" v-model="value">
      <button type="submit">입력</button>
    </form>
    <div>시도: {{tries.length}}</div>
    <ul>
      <li v-for="t in tries">
        <div>{{t.try}}</div>
        <div>{{t.result}}</div>
      </li>
    </ul>
  </div>    
</template>

<script>
  const getNumbers = () => {
    const candidates = [1, 2, 3, 4, 5, 6, 7, 8, 9]
    const array = []
    for (let i = 0; i < 4; i += 1) {
      const chosen = candidates.splice(Math.floor(Math.random() * (9 - i)), 1)[0]
      array.push(chosen)
    }
    return array
  }

export default { // 이 부분이 Vue.component 부분
  data() {
    return {
      answer: getNumbers(), // ex) [1, 5, 3, 4]
      tries: [],  // 시도 수
      value: '',  // 입력
      result: '',  // 결과
    }
  },
  methods: {
    onSubmitForm() {
      if (this.value === this.answer.join('')) {
        this.tries.push({
          try: this.value,
          result: '홈런'
        })
        this.result = '홈런'
        alert('게임을 다시 실행합니다.')
        this.value = ''
        this.answer = getNumbers()
        this.tries = []
        this.$refs.answer.focus()
      } else {
        if (this.tries.length >= 9) {
          this.result = `10번 넘게 틀려서 실패! 답은 ${this.answer.join(',')}였습니다!`
          alert('게임을 다시 실행합니다.')
          this.value = ''
          this.answer = getNumbers()
          this.tries = []
          this.$refs.answer.focus()
        }
        let strike = 0 
        let ball = 0
        const answerArray = this.value.split('').map(v => parseInt(v)) //'1234' 를 숫자배열로 바꾸는 코드
        for (let i = 0; i < 4; i +=1) {
          if (answerArray[i] === this.answer[i]) {  // 숫자 자릿수 모두 정답
            strike++
          } else if( this.answer.includes(answerArray[i])) { // 숫자만 정답
            ball++
          }
        }
        this.tries.push({
          try: this.value,
          result: `${strike} 스트라이크, ${ball} 볼입니다.`
        })
      }

      this.value = ''
      this.$refs.answer.focus()
    }
  }
}
</script>

<style>

</style>

// React/webGame/3_숫자야구/NumberBaseball.jsx
const React = require('react')
const { memo } = require('react')
const { useRef, useState } = require('react')
const Try  = require('./Try')

function getNumbers() { 
  const candidate = [1, 2, 3, 4, 5, 6, 7, 8, 9]
  const array = []
  for (let i = 0; i < 4; i += 1) {
    const chosen = candidate.splice(Math.floor(Math.random() * (9 - i)), 1)[0]
    array.push(chosen)
  }
  return array
}

const NumberBaseball = memo(() => {
  const [result, setResult] = useState('')
  const [value, setValue] = useState('')
  const [answer, setAnswer] = useState(getNumbers())
  const [tries, setTries] = useState([])
  const inputEl = useRef(null)

  const onSubmitForm = (e) => {
    e.preventDefault()
    if (value.length !== 4) {
      alert('숫자 4개를 입력해주세요')
      setValue('')
      return
    }
    if ( value === answer.join('')) { 
      setResult('홈런')
      setTries((prevTries) => {
        return [...prevTries, { try: value, result: '홈런!' }]
      })
      alert('게임을 다시 시작합니다!')
      setValue('')
      setAnswer(getNumbers())
      setTries([])
      inputEl.current.focus()
    } else { 
      const answerArray = value.split('').map(v => parseInt(v))
      let strike = 0
      let ball = 0
      if (tries.length >= 9) { 
        setResult(`10번 넘게 틀려서 실패! ${answer.join(',')} 였습니다.`)
        alert('게임을 다시 시작합니다!')
        setValue('')
        setAnswer(getNumbers())
        setTries([])
        inputEl.current.focus()
      } else {
        for (let i = 0; i < 4; i +=1 ) {
          if (answerArray[i] === answer[i]) {
            console.log('스트라이크')
            strike += 1
          } else if (answer.includes(answerArray[i])) {
            console.log('볼')
            ball += 1
          }
        }
        setTries((prevTries) => {
          return [...prevTries, { try: value, result: `${strike}스트라이크, ${ball}볼입니다.`}]
        })
        setValue('')
        inputEl.current.focus()
      }
    }
  }
  const onChangeInput = (e) => {
    setValue(e.target.value)
  }

  return (
    <>
      {/* jsx 주석 */}
        <h1>{result}</h1>
        <form onSubmit={onSubmitForm}>
          <input maxLength={4} value={value} onChange={onChangeInput} />
        </form>
        <div>시도: {tries.length}</div>
        <ol>
          {tries.map((v, i) => {
            return (
              <Try key={`${i + 1}차 시도 : `} tryInfo={v} />
            )
          })}
        </ol>
      </>    
  )
})

module.exports = NumberBaseball
