// React/webGame/7_틱택토/Table.jsx
import React, { memo } from 'react'
import Tr from './Tr'

const Table = memo(({ onClick, tableData, dispatch }) => {
  return (
    <table>
      {Array(tableData.length).fill().map((tr, i) => (<Tr key={i} dispatch={dispatch} rowIndex={i} rowData={tableData[i]}/>))}
    </table>
  )
})

export default Table

// Vue/webGame/7_틱택토/tableComponent.vue
<template>
  <table>
    <tr-component v-for="(rowData, index) in tableData" :row-data="rowData" :row-index="index" :key="index"></tr-component>
  </table>
</template>

<script>
  import trComponent from './trComponent'

export default {
  props: {
    tableData: Array
  },
  components: {
    trComponent,
  },
  data() {
    return {

    }
  }
}
</script>

<style scoped>

</style>
