// Vue/webGame/4_반응속도체크/responseCheck.vue
<template>
  <div>
    <div id="screen" v-bind:class="state" @click="onClickScreen">{{message}}</div>
    <template v-if="result.length">
      <div>평균시간: {{average}}ms</div>
      <button @click="onReset">리셋</button>
    </template>
  </div>    
</template>

<script>
  let startTime = 0
  let endTime = 0
  let timeout = null
  export default { // 이 부분이 Vue.component 부분
    data() {
      return {
        result: [],
        state: 'waiting',
        message: '클릭해서 시작하세요.',
  }
    },
    computed: {
      average() {
        return this.result.reduce((a,c) => a + c, 0) / this.result.length || 0
      }
    },
    methods: {
      onReset() {
        this.result = []
      },
      onClickScreen() {
        if (this.state === 'waiting') {
          this.state = 'ready'
          this.message = '초록색이 되면 클릭하세요.'
          timeout = setTimeout(() => {
            this.state = 'now'
            this.message = '지금 클릭!'
            startTime = new Date()
          }, Math.floor(Math.random() * 1000) + 2000) // 2~3초
        } else if (this.state === 'ready') {
          clearTimeout(timeout)
          this.state = 'waiting'
          this.message = '너무 성급하시군요! 초록색이 된 후에 클릭하세요'
        } else if (this.state === 'now') {
          endTime = new Date()
          this.state = 'waiting'
          this.message = '클릭해서 시작하세요'
          this.result.push(endTime - startTime)
        }
      }
    }
  }
</script>

<style scoped>
  #screen {
    width: 300px;
    height: 200px;
    text-align: center;
    user-select: none;
  }
  #screen.waiting {
    background-color: aqua;
  }
  #screen.ready {
    background-color: red;
    color: white;
  }
  #screen.now {
    background-color: greenyellow;
  }
</style>

// React/webGame/4_반응속도체크/ResponseCheck.jsx
import React, { Component } from 'react'

class ResponseCheck extends Component {
  state = {
   state: 'waiting',
   message: '클릭해서 시작하세요.',
   result: [],
  }

  timeout
  startTime
  endTime

  onClickScreen = () => {
    const { state, message, result } = this. state
    if ( state === 'waiting' ) {
      this.setState({
        state: 'ready',
        message: '초록색이 되면 클릭하세요.'
      })
      this.timeout = setTimeout(() => {
        this.setState({
          state: 'now',
          message: '지금 클릭하세요'
        })
        this.startTime = new Date()
      }, Math.floor(Math.random() * 1000) + 2000) // 2초 ~ 3초 랜덤
    }else if (state === 'ready') { // 성급한 클릭
      clearTimeout(this.timeout)
      this.setState({
        state: 'waiting',
        message: '너무 성급하셨군요! 초록색이 된 후에 클릭하세요'
      })      
    }else if ( state === 'now' ) { // 반응속도 체크 
      this.endTime = new Date()
      this.setState((prevState) => {
        return {
          state: 'waiting',
          message: '클릭해서 시작하세요',
          result: [...prevState.result,  this.endTime - this.startTime]          
        }
      })
    }
  }

  onReset = () => {
    this.setState({
      result: []
    })
  }

  renderAverage = () => {
    const { result } = this.state

    return result.length === 0 
    ? null  // false, undefined, null은 jsx에서 태그없음을 의미한다.
    : <>
      <div>평균시간: {result.reduce((a, c) => a + c) / result.length}ms</div> 
      <button onClick={this.onReset}>리셋</button>  
    </>
  }

  render() {
    const { state, message } = this.state
    return (
      <>
        <div
          id="screen"
          className={state}
          onClick={this.onClickScreen}
        >
          {message}  
        </div>
        { this.renderAverage() }
      </>
    )
  }
}

export default ResponseCheck
