// React/webGame/7_틱택토/Table.jsx
import React, { memo } from 'react'
import Tr from './Tr'

const Table = memo(({ onClick, tableData, dispatch }) => {
  return (
    <table>
      {Array(tableData.length).fill().map((tr, i) => (<Tr key={i} dispatch={dispatch} rowIndex={i} rowData={tableData[i]}/>))}
    </table>
  )
})

export default Table

// Vue/11_지뢰찾기/tableComponent.vue
<template>
  <table>
    <tr v-for="(rowData, rowIndex) in tableData" :key="rowIndex">
      <td v-for="(cellData, cellIndex) in rowData" :key="cellIndex">{{cellData}}</td>
    </tr>
  </table>
</template>

<script>
  import { mapState } from 'vuex'

  export default {
    computed: {
      ...mapState(['tableData'])
    }
  }
</script>
